/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package footballboard;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
/**
 *
 * @author Patberg
 */
public class FirstFrame extends javax.swing.JFrame {

    TeamModifications teamMods = new TeamModifications();
    GeneralSettingsModifications genMods = new GeneralSettingsModifications();
    /**
     * Creates new form FirstFrame
     */
    public FirstFrame() {
        initComponents();
        this.getContentPane().setBackground(Color.white);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LeagueSettingsLabel = new javax.swing.JLabel();
        LeagueSettingPanel = new javax.swing.JPanel();
        TeamTextField = new javax.swing.JTextField();
        AddTeamsButton = new javax.swing.JButton();
        RoundTextField = new javax.swing.JTextField();
        TeamList = new javax.swing.JComboBox();
        RemoveTeamButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        TeamRosterPanel = new javax.swing.JPanel();
        QBTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        RBLabel = new javax.swing.JLabel();
        RBTextField = new javax.swing.JTextField();
        WRTextField = new javax.swing.JTextField();
        WRLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        TELabel = new javax.swing.JLabel();
        RBWRTETextField = new javax.swing.JTextField();
        TETextField = new javax.swing.JTextField();
        WRLabel1 = new javax.swing.JLabel();
        KLabel = new javax.swing.JLabel();
        KTextField = new javax.swing.JTextField();
        DefLabel = new javax.swing.JLabel();
        DefTextField = new javax.swing.JTextField();
        SetPicksButton = new javax.swing.JButton();
        StartDraftButton = new javax.swing.JButton();
        AddPlayerButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LeagueSettingsLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LeagueSettingsLabel.setText("Enter the league settings");

        LeagueSettingPanel.setOpaque(false);

        TeamTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TeamTextFieldActionPerformed(evt);
            }
        });

        AddTeamsButton.setText("Add Team");
        AddTeamsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddTeamsButtonActionPerformed(evt);
            }
        });

        RoundTextField.setText("15");

        RemoveTeamButton.setText("Remove Team");
        RemoveTeamButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveTeamButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Rounds:");

        javax.swing.GroupLayout LeagueSettingPanelLayout = new javax.swing.GroupLayout(LeagueSettingPanel);
        LeagueSettingPanel.setLayout(LeagueSettingPanelLayout);
        LeagueSettingPanelLayout.setHorizontalGroup(
            LeagueSettingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeagueSettingPanelLayout.createSequentialGroup()
                .addGroup(LeagueSettingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TeamTextField)
                    .addComponent(TeamList, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LeagueSettingPanelLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RoundTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(LeagueSettingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddTeamsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(LeagueSettingPanelLayout.createSequentialGroup()
                        .addComponent(RemoveTeamButton)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        LeagueSettingPanelLayout.setVerticalGroup(
            LeagueSettingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeagueSettingPanelLayout.createSequentialGroup()
                .addGroup(LeagueSettingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TeamTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddTeamsButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(LeagueSettingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TeamList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RemoveTeamButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(LeagueSettingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RoundTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)))
        );

        ArrayList<String> teams = teamMods.getTeams();

        for(int x = 0; x<teams.size(); x++)
        TeamList.addItem(teams.get(x));

        TeamRosterPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TeamRosterPanel.setOpaque(false);

        QBTextField.setText("1");

        jLabel2.setText("QB:");

        RBLabel.setText("RB: ");

        RBTextField.setText("2");

        WRTextField.setText("2");
        WRTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WRTextFieldActionPerformed(evt);
            }
        });

        WRLabel.setText("WR:");

        jLabel1.setText("How many starters does each team ?");

        TELabel.setText("TE:");

        RBWRTETextField.setText("1");
        RBWRTETextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBWRTETextFieldActionPerformed(evt);
            }
        });

        TETextField.setText("1");
        TETextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TETextFieldActionPerformed(evt);
            }
        });

        WRLabel1.setText("RB/WR/TE:");

        KLabel.setText("K:");

        KTextField.setText("1");
        KTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KTextFieldActionPerformed(evt);
            }
        });

        DefLabel.setText("Def:");

        DefTextField.setText("1");
        DefTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DefTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TeamRosterPanelLayout = new javax.swing.GroupLayout(TeamRosterPanel);
        TeamRosterPanel.setLayout(TeamRosterPanelLayout);
        TeamRosterPanelLayout.setHorizontalGroup(
            TeamRosterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TeamRosterPanelLayout.createSequentialGroup()
                .addGroup(TeamRosterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TeamRosterPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(TeamRosterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(TeamRosterPanelLayout.createSequentialGroup()
                                .addComponent(KLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(KTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TeamRosterPanelLayout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(QBTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TeamRosterPanelLayout.createSequentialGroup()
                                .addComponent(TELabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(TETextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TeamRosterPanelLayout.createSequentialGroup()
                                .addComponent(RBLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(RBTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TeamRosterPanelLayout.createSequentialGroup()
                                .addComponent(WRLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(WRTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(TeamRosterPanelLayout.createSequentialGroup()
                                .addComponent(DefLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(DefTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(49, 49, 49)
                        .addComponent(WRLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RBWRTETextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TeamRosterPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)))
                .addContainerGap())
        );
        TeamRosterPanelLayout.setVerticalGroup(
            TeamRosterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TeamRosterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(TeamRosterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(QBTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(WRLabel1)
                    .addComponent(RBWRTETextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(TeamRosterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RBLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(RBTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(TeamRosterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(WRLabel)
                    .addComponent(WRTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TeamRosterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TETextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TELabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TeamRosterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(KTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(KLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TeamRosterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DefTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DefLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        SetPicksButton.setText("Set Picks");
        SetPicksButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SetPicksButtonActionPerformed(evt);
            }
        });

        StartDraftButton.setText("Start Draft");
        StartDraftButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartDraftButtonActionPerformed(evt);
            }
        });

        AddPlayerButton.setText("Add Player");
        AddPlayerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddPlayerButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(LeagueSettingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AddPlayerButton)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(SetPicksButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(StartDraftButton)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(TeamRosterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(LeagueSettingsLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LeagueSettingsLabel)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(LeagueSettingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SetPicksButton)
                            .addComponent(StartDraftButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(TeamRosterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AddPlayerButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddTeamsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddTeamsButtonActionPerformed
             
        teamMods.addNewTeam(TeamTextField.getText());
        TeamList.addItem(TeamTextField.getText());
        TeamTextField.setText("");
        TeamTextField.requestFocus();
        
    }//GEN-LAST:event_AddTeamsButtonActionPerformed

    private void TeamTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TeamTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TeamTextFieldActionPerformed

    private void WRTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WRTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WRTextFieldActionPerformed

    private void RBWRTETextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBWRTETextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RBWRTETextFieldActionPerformed

    private void TETextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TETextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TETextFieldActionPerformed

    private void KTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KTextFieldActionPerformed

    private void DefTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DefTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DefTextFieldActionPerformed

    private void RemoveTeamButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveTeamButtonActionPerformed
        teamMods.removeTeam((String)TeamList.getSelectedItem());
        TeamList.removeItem((String)TeamList.getSelectedItem());
    }//GEN-LAST:event_RemoveTeamButtonActionPerformed

    private void SetPicksButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SetPicksButtonActionPerformed
        try
        {
            genMods.add("QB",Integer.parseInt(QBTextField.getText()));
            genMods.add("RB",Integer.parseInt(RBTextField.getText()));
            genMods.add("WR",Integer.parseInt(WRTextField.getText()));
            genMods.add("TE",Integer.parseInt(TETextField.getText()));
            genMods.add("DEF",Integer.parseInt(DefTextField.getText()));
            genMods.add("K", Integer.parseInt(KTextField.getText()));
            genMods.add("Rounds",Integer.parseInt(RoundTextField.getText()));
            genMods.add("RB/WR/TE",Integer.parseInt(RBWRTETextField.getText()));

            SetPicksGUI picks = new SetPicksGUI();
            picks.setVisible(true);
            picks.setDefaultCloseOperation(DISPOSE_ON_CLOSE);  
            this.dispose();
        }
        catch(NumberFormatException e)
        {
            JOptionPane.showMessageDialog(this, "Enter integers into the boxes before proceeding to pick setup.");
        }
    }//GEN-LAST:event_SetPicksButtonActionPerformed

    private void StartDraftButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartDraftButtonActionPerformed
        
        
        if(!teamMods.getTeamsWithOutPick().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Every team needs a draft pick before proceeding to the draft.");
        }
        else
        {
            try
            {
                genMods.add("QB",Integer.parseInt(QBTextField.getText()));
                genMods.add("RB",Integer.parseInt(RBTextField.getText()));
                genMods.add("WR",Integer.parseInt(WRTextField.getText()));
                genMods.add("TE",Integer.parseInt(TETextField.getText()));
                genMods.add("DEF",Integer.parseInt(DefTextField.getText()));
                genMods.add("K", Integer.parseInt(KTextField.getText()));
                genMods.add("Rounds" ,Integer.parseInt(RoundTextField.getText()));
                genMods.add("RB/WR/TE",Integer.parseInt(RBWRTETextField.getText()));


                DraftGUI draftGui = new DraftGUI();
                draftGui.setDefaultCloseOperation(EXIT_ON_CLOSE);
                draftGui.setVisible(true);
                this.dispose();
            }
            catch(NumberFormatException e)
            {
                JOptionPane.showMessageDialog(this, "You need to only enter integers into the input boxes.");
            }
        }
    }//GEN-LAST:event_StartDraftButtonActionPerformed

    private void AddPlayerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddPlayerButtonActionPerformed
        AddPlayerGUI picks = new AddPlayerGUI();
        picks.setVisible(true);
        picks.setDefaultCloseOperation(DISPOSE_ON_CLOSE); 
        this.dispose();
    }//GEN-LAST:event_AddPlayerButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FirstFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FirstFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FirstFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FirstFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FirstFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddPlayerButton;
    private javax.swing.JButton AddTeamsButton;
    private javax.swing.JLabel DefLabel;
    private javax.swing.JTextField DefTextField;
    private javax.swing.JLabel KLabel;
    private javax.swing.JTextField KTextField;
    private javax.swing.JPanel LeagueSettingPanel;
    private javax.swing.JLabel LeagueSettingsLabel;
    private javax.swing.JTextField QBTextField;
    private javax.swing.JLabel RBLabel;
    private javax.swing.JTextField RBTextField;
    private javax.swing.JTextField RBWRTETextField;
    private javax.swing.JButton RemoveTeamButton;
    private javax.swing.JTextField RoundTextField;
    private javax.swing.JButton SetPicksButton;
    private javax.swing.JButton StartDraftButton;
    private javax.swing.JLabel TELabel;
    private javax.swing.JTextField TETextField;
    private javax.swing.JComboBox TeamList;
    private javax.swing.JPanel TeamRosterPanel;
    private javax.swing.JTextField TeamTextField;
    private javax.swing.JLabel WRLabel;
    private javax.swing.JLabel WRLabel1;
    private javax.swing.JTextField WRTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
